# This is a basic workflow to help you get started with Actions

name: CI
env:
  AWS: ${{ secrets.AWS }}
  VAR1: ${{ vars.VAR1 }}
  VAR2: ${{ vars.VAR2 }}
  VAR3: ${{ vars.VAR3 }}
 
 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
      - master 
      - dev 
  pull_request:
    branches: 
      - master
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v2
    - name: bash
      run: |
        echo "AWS: ${{ secrets.AWS }}"
        echo "VAR1: ${{ ENV.VAR1 }}"
        echo "VAR2: ${{ ENV.VAR2 }}"
        echo "VAR3: ${{ ENV.VAR3 }}"
        echo "---------------------"
        echo "AWS: $AWS"
        echo "VAR1: $VAR1"
        echo "VAR2: $VAR2 "
        echo "VAR3: $VAR3 "
        
        


     
