# This is a basic workflow to help you get started with Actions

name: CI

 
 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: 
      - master 
      - dev 
  pull_request:
    branches: 
      - master
      - dev
env:
  AWS: ${{ secrets.AWS }}
  VAR1: ${{ vars.VAR1 }}
  VAR2: ${{ vars.VAR2 }}
  VAR3: ${{ vars.VAR3 }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.base_ref }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v2
    - name: bash
      run: |
        echo "AWS: ${{ secrets.AWS }}"
        echo "VAR1: ${{ VARS.VAR1 }}"
        echo "VAR2: ${{ VARS.VAR2 }}"
        echo "VAR3: ${{ VARS.VAR3 }}"
        echo "---------------------"
        echo "AWS: $AWS"
        echo "VAR1: $VAR1"
        echo "VAR2: $VAR2 "
        echo "VAR3: $VAR3 "
        echo "${{ github.base_ref }}"
        
        


     
