
name: Test Devops

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches:
      - dev
      - master
    # paths-ignore:
    #   - '.github/**'




# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    environment: CURSO
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          ls -la
          pwd
          # terraform
          echo "$VAR"
        env:
          VAR: ${{ secrets.SECRETO }}
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          ls -la
          pwd
          # terraform
          echo Hello, world!
          echo "test"

        
        


     
